### ISSUE TITLE
Support Periodic Bib Sync

### ISSUE THREAD

**Issue by mattave** [RunSignUp-Team/RunSignup-Mobile-Timing-App#38]
Reported by Scott Sutter:

> The only problems we ran into with the App were (that may have been user error):
> 
> The bib number for one runner (Ken Clark #364) did not appear in the grid view.
> Doesn’t appear the App fully synced with the Check-In App.

Resolution for now is to simply toggle back to normal entry mode and back into bib grid mode. In the future we may want to support a true sync model to ensure that bib numbers are up to date in the app.

**Comment by nathanael-rsu** [comment]
Closing in favor of #39, because they are very related. #39 will add both a manual refresh and an auto refresh every minute.
