### ISSUE TITLE
Backup App Mode

### ISSUE THREAD

**Issue by nathanael-rsu** [RunSignUp-Team/RunSignup-Mobile-Timing-App#39]
We will support a third mode, in addition to Online Races and Offline Events. This third "Backup Mode" will allow the user to sync down participant information and bib numbers (so that they can see participant names in Results Mode and use the Grid View in Finish Line Mode), but it will never sync any information up to RSU. The only way users will be able to get information out of this mode is to export it themselves. As part of this update, we will add support for periodic syncing of Bib Numbers when in Grid View.

**Comment by mattave** [comment]
Requested by Eric Kramer:

> If there would be a plan to not automatically sync with online results, I could see a great benefit for being able to utilize already assigned bib numbers

Public Ticket URL: https://help.runsignup.com/support/tickets/public/a1243dc0b3393b2259fa5be5a8d1b1573e0d20b27cf0fbc93c14a0307486df66

**Comment by mattave** [comment]
Reminder to followup with Lowell Ladd when complete: https://runsignup.freshdesk.com/a/tickets/1045212
