### ISSUE TITLE
Add Support for Hardware Keyboard

### ISSUE THREAD

**Issue by nathanael-rsu** [RunSignUp-Team/RunSignup-Mobile-Timing-App#43]

**Comment by mattave** [comment]
I may order one of these to try out: https://www.amazon.com/Sunreed-Calculator-Bluetooth-Financial-Accounting/dp/B08Y728NJV/ref=sr_1_1_sspa?crid=W32P6BJTEER1&keywords=bluetooth+number+pad+android+ios&qid=1660154912&s=electronics&sprefix=bluetooth+number+pad+android+ios%2Celectronics%2C48&sr=1-1-spons&psc=1

I like how it will display the numbers you are typing in on the LCD panel so it will be easier for operators to verify that they are entering the bib correctly before submitting. I'll have to test to ensure that the enter key would be mapped to the record button correctly.

**Comment by mattave** [comment]
I got the bluetooth num pad and have been testing it. The main issue is that I would like the enter key to be able to select the "Record" button in both finish line and chute modes. 

I also noticed that on Android I was not able to get the bib entry field to select itself again, but on iOS if you clicked the enter key twice it would re-select the bib field.

**Comment by nathanael-rsu** [comment]
I have been able to get this mostly working after our conversation last night. I realized what the main problem was with selecting the Text Input was. It was more obviously an issue on Android, but it was also causing issues on iOS.

Now, after initially tapping the Text Input with your finger in Finish Line Mode (in Chute Mode, we auto-focus the Text Input so you don't even have to do that), you can type in the bibs as you would expect, hit enter, and the Text Input is re-selected for the next bib entry. The only "issue" currently is that if you hit enter twice in a row, it de-selects the Text Input, and I don't think I can keep that from happening. However, hitting enter a third time re-selects the Text Input, so I don't think it's a huge deal.

**Comment by mattave** [comment]
Cool - is enter now selecting "Record" for you?

**Comment by nathanael-rsu** [comment]
It doesn't "select" Record -- it just records when you hit enter, and then re-selects the Text Input.

**Comment by mattave** [comment]
See issue with Lou King: https://runsignup.freshdesk.com/a/tickets/1126675

Public Ticket URL: https://help.runsignup.com/support/tickets/public/b3c960f054266cadbf1cc9fb3e9fa262259bddf0292bb822fd8ce3cf3f701bc5

> I have to touch the phone to select the Bib Entry field for each result. I was hoping the Bluetooth keypad could be used like a Time Machine away from the phone, but I don't see how.


I also see an issue with Android when trying to enter in numbers with the Bluetooth numpad. After clicking "Enter" the cursor does not go back to the entry form and I have to tap to get back into it.

**Comment by nathanael-rsu** [comment]
Not sure if we had some miscommunication on this or not -- I thought we had said to wait on getting the hardware keyboard support until v1.0.8 because we were trying to get v1.0.7 out before the webinar. I honestly forgot so I didn't catch that we said we supported it in the Start Guide.

**Comment by mattave** [comment]
No worries - we'll just get that change into the next build.

**Comment by allisoncarignan** [comment]
Feedback from Lou King on using an external keyboard with the timing app

While in finish line mode:

"I have to click on the Bib Entry field on the phone before the first keypad numbers are pressed. Maybe that's ok, but I can see that could cause problems at the start of a race.
There is no way from the keypad to record a time without a bib number. When I press the enter button, the app screen goes dim for a split second, but no time is recorded
If I click the Record button on the app to record a result without bib number, I have to click back into the Bib Entry field for the keypad input to be recognized again


My expectation was that the keypad operator wouldn't have to look at, clicking on, the phone app during the race, i.e., that once the phone and keypad were connected that the keypad would act like a Time Machine."

Public Ticket URL: https://help.runsignup.com/support/tickets/public/b3c960f054266cadbf1cc9fb3e9fa262259bddf0292bb822fd8ce3cf3f701bc5
