### ISSUE TITLE
Fix iOS App Name

### ISSUE THREAD

**Issue by nathanael-rsu** [RunSignUp-Team/RunSignup-Mobile-Timing-App#48]
I think the name on iOS is too long on the Home Screen. Can this be fixed?
![IMG_3943](https://user-images.githubusercontent.com/97470828/184211036-af03686a-c863-409a-9538-3b366f5eb22f.jpg)

**Comment by nathanael-rsu** [comment]
Might be applicable: https://stackoverflow.com/questions/67475232/how-to-change-app-display-name-in-expo-managed-app-after-publishing-to-app-store

**Comment by lepertRSU** [comment]
Nathanael I already made the change and it is seen in last Test Flight build.  That is why I changed the label to Needs Testing

**Comment by nathanael-rsu** [comment]
Oh, cool! Somehow I totally missed that -- looks good on both Android and iOS for me. I'm glad Expo allowed that functionality.
